### ISSUE TITLE
bad use of duplicate id on elements

### ISSUE THREAD

**Issue by urkle** [pboling/rack-insight#43]
For example using request_id_menu on several select elements does not work in modern browsers.  And doing ``` $('#request_id_menu') ``` only selects one of them causing the dropdowns to not function most of the time.  IDs on HTML elements are supposed to be unique across the entire page..   If you want multiple elements to be referenced you should use a class.  e.g.

``` $('#rack-insight .request_id_menu') ```

instead

``` $('#request_id_menu') ```

**Comment by pboling** [comment]
You are completely correct, and there is a lot of old crufty stuff there.

The HTML and JS of this project has been hardly touched since it was Rack-Bug.  It needs a complete overhaul.  Help is appreciated.  I don't often have time to work on Rack-Insight, and when I do I focus on the back-end needs.
